### ISSUE TITLE
Multi-Site-Installation

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-robots-txt-editor#1]
Für eine Seite ist das so schon mal sehr gut, aber da könnte ich es ja auch ganz einfach manuell bearbeiten. Jetzt müssen wir den nächsten Schritt gehen: Multi-Site-Installation! Denn da wird es ja erst richtig interessant. Folgendes sollte da passieren:
1. Import der Default-robots.txt bleibt unverändert, aber beim Speichern muss nun folgendes passieren:
   - ablegen der individuellen robots.txt unter share/robots_domain-a-tld.txt
   - anlegen einer rewrite-Regel `RewriteCond %{HTTP_HOST} ^(www\.)?domain-a\.tld$
     RewriteRule ^robots\.txt share/robots_domain-a-tld\.txt` in der htaccess via hofff/contao-htaccess
2. Wenn man die Option "Add absolute sitemap path to robots.txt" aktiviert, muss nun der Pfad in die individuelle share/robots_domain-a-tld.txt geschrieben werden.

**Comment by cliffparnitzky** [comment]
First parts are implemented in a001cd063726f1f1fa16e2985059fd4275e34a09, 83ba189932ce2ec02aef8fa72caddf12259fdb9f, 680d2ad1f99f41ad383818002ff6e164e9394c32 and 3387b4cb4d5ab40d475f1f0cdc5607352fe13ff2

**Comment by cliffparnitzky** [comment]
Cleaning up old robots.txt: 021728e7ad01dd5cd1439a5f05e4f6bfb45111ca

**Comment by cliffparnitzky** [comment]
Build in with https://github.com/hofff/contao-robots-txt-editor/commit/3b9be7def92fc313924474388b927b90cffa8c2f
