### ISSUE TITLE
Check Contao 4.4 default content

### ISSUE THREAD

**Issue by cliffparnitzky** [hofff/contao-robots-txt-editor#5]
Pleas check the Contao 4.4 default content at: https://github.com/hofff/contao-robots-txt-editor/blob/hotfix/1.1.1/CT_ROOT/system/modules/hofff_robots-txt-editor/config/config.php#L11-L13

**Comment by frontendschlampe** [comment]
I just check the default entries and after consultation with @discordier it's enough to make the following entries:

```
User-agent: *
Disallow: /check/
Disallow: /contao-manager.phar.php
```

See https://github.com/hofff/contao-robots-txt-editor/commit/cdb72055fdb8cec9822a3cd64ef6a7792e40f3a7

**Comment by cliffparnitzky** [comment]
Great. When #4 was successfully, we can close this.

**Comment by frontendschlampe** [comment]
Actually the Contao Check doesn't work with Contao 4, but I think, it should not be a problem when we disallow it by default. We will see ...
